### ISSUE TITLE
Restore to different name

### ISSUE THREAD

**Issue by amarc** [minio/lxmin#11]
Hello and thank you for, what seems, great tool.

I would like to have: 

- restore to different name: lxmin restore cont cont2 backup_2022-05-11-18-1704 (where cont is current container running and cont2 is new, non-existing one)
- similar to above, have --force or similar to overwrite existing container/vm
- have (global) configuration file instead of export variables 

A.

**Comment by harshavardhana** [comment]
This is out of scope @amarc since we keep profiles as well - renaming them as a separate VM name is something we have no interest in supporting right now. 

Feel free to work on this on your own and submit a PR we can take a look if it's clean.

> * similar to above, have --force or similar to overwrite existing container/vm

Out of scope

> * have (global) configuration file instead of export variables

On purpose not implemented, built for cloud-native - environment variable first deployment. No config.
